### PR TITLE
Added AbstractPerceptron id

### PR DESCRIPTION
**Pull request by vntxx**
for easier access to deterministic savefile

### CODE REVIEW

**Review by EricMiddelhove — COMMENTED** [review]
I dont see why this is neccessary

**Comment by vntxx** [comment]
There's why

**Comment by vntxx** [comment]
That's why it's in Abstract Perceptron

**Comment by vntxx** [comment]
What does more dynamic mean to you, what additional functionality do you want

**Comment by EricMiddelhove** [comment]
> What does more dynamic mean to you, what additional functionality do you want

Just put the Perceptrons to save into an array as param and iterate through so we will have more freedom in terms of what we want so safe

**Comment by vntxx** [comment]
That's what i meant in #8 by using a superclass for Network

**Comment by vntxx** [comment]
This pr is just for adding the id's so could you please merge this and i'll add the rest independently

**Pull request merged**
