### PR TITLE
Network upgrade

### PR DESCRIPTION
**Pull request by vntxx**

### CODE REVIEW

**Comment by EricMiddelhove** [comment]
Can you explain me an amazing reason why this is neccessary?

**Comment by vntxx** [comment]
Providing modularity if you eventually want to add another network
I could also modify this to use an interface if you like

**Comment by EricMiddelhove** [comment]
> Providing modularity if you eventually want to add another network
> I could also modify this to use an interface if you like

this is not the goal of the project so i would decline this change to keep the complexity as small as possible

**Comment by vntxx** [comment]
I'll close #8 as well

**Comment by vntxx** [comment]
You could also just keep the branch and if you change your mind you're free to just merge it

**Pull request closed without merging**
